params:
  youtube_channel_ids:
    - UCCezIgC97PvUuR4_gbFUs5g
    - UCa9gErQ9AE5jT2DZLjXBIdA
    - UCXUPKJO5MZQN11PqgIvyuvQ
    - UCDq7SjbgRKty5TgGafW8Clg
    - UC5_6ZD6s8klmMu9TXEB_1IA
    - UCgBncpylJ1kiVaPyP-PZauQ
    - UCgLxmJ8xER7Y7sywMN5SfWg
    - UCoW_WzQNJVAjxo4osNAxd_g
    - UCG04dVOTmbRYPY1wvshBVDQ
    - UCnnQ3ybuyFdzvgv2Ky5jnAA
    - UCtAcpQcYerN8xxZJYTfWBMw
    - UCbXgNpp0jedKWcQiULLbDTA
    - UCYO_jab_esuFRV4b17AJtAw
    - UCOsGw17tMhM4-GBjvQnXGzQ
    - UC6P9lh2AN6hYC1mi97aU9HA
    - UC8wZnXYK_CGKlBcZp-GxYPA
    - UCAq9f7jFEA7Mtl3qOZy2h1A
    - UC9xKdy8cz6ZuJU5FTNtM_pQ
    - UC_CzsS7UTjcxJ-xXp1ftxtA
    - UCKeh7bpt9X9HxBd6TyGzqQg
    - UCaiL2GDNpLYH6Wokkk1VNcg
    - UCswGK0lhZXiN8RFjEUFTUWw
    - UCu7lQE-L5gzt8aD7zuuufjw
    - UCdEov4L0bpJ_h6W3sJxkfUA
  max_results: 50
